osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
  - "$HOME/.npm"
addons:
  apt:
    update: true
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - libcups2-dev
    - graphicsmagick
    - xz-utils
before_install:
- export LANG=en_US.UTF-8
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- nvm install 8
- nvm use 8
- source ~/.bashrc
install:
- npm install -g xvfb-maybe
- npm install -g npm@latest
- npm install
script:
- npm run build
branches:
  only:
  - master
