version: 0.1.{build}

environment:
  nodejs_version: "8.11.3"
  GH_TOKEN: 1FMwnJoqZUKuGuCgElp4LdpmflJIUaODB5elKK8mtkgUPzYApozF4iQ2X7a9vbKt
  APPVEYOR_YML_DISABLE_PS_LINUX: true

image:
  - Visual Studio 2015
  - Ubuntu

platform:
  - x86
  - x64

matrix:
  exclude:
  - image: Visual Studio 2015
    platform: x64
  - image: Ubuntu
    platform: x86

cache:
  # - node_modules
  # - '%USERPROFILE%\.electron'
  # - '%USERPROFILE%\.electron-gyp'
  # - '%USERPROFILE%\AppData\Local\electron\Cache'
  # - '%USERPROFILE%\AppData\Local\electron-builder\cache'
  # - '%AppData%\npm-cache\'

init:
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y libcups2-dev
  - cmd: git config --global core.autocrlf input

stack: node 8, python 2.7.14

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm install

build_script:
  - npm run build

test: off

deploy: off
