version: 0.1.{build}

environment:
  nodejs_version: "8.11.2"
  GH_TOKEN: 1FMwnJoqZUKuGuCgElp4LdpmflJIUaODB5elKK8mtkgUPzYApozF4iQ2X7a9vbKt
  APPVEYOR_YML_DISABLE_PS_LINUX: true

branches:
  only:
    - master

image:
  - Visual Studio 2015
  - Ubuntu

platform:
  - x86
  - x64

matrix:
  exclude:
  - image: Visual Studio 2015
    platform: x64
  - image: Ubuntu
    platform: x86

cache:
  # - node_modules
  # - '%USERPROFILE%\.electron'
  # - '%USERPROFILE%\.electron-gyp'
  # - '%USERPROFILE%\AppData\Local\Yarn\cache'
  # - '%USERPROFILE%\AppData\Local\electron\Cache'
  # - '%USERPROFILE%\AppData\Local\electron-builder\cache'

init:
  - cmd: git config --global core.autocrlf input

stack: node 8

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

build_script:
  - yarn build

test: off

artifacts:
  - path: build\*.exe
    name: his-client

deploy: off
